env_files = [
    "./.cargomake.env"
]

[config]
skip_core_tasks = true

[tasks.zenn]
script = [
'''
#!/bin/bash
docker run --rm -v $(pwd):/work ${IMAGE} ${@}
'''
]

[tasks.attach]
script = [
'''
#!/bin/bash
docker run --rm -it -v $(pwd):/work --entrypoint "/bin/ash" ${IMAGE}
'''
]

[tasks.tl]
script = [
'''
#!/bin/bash
docker run --rm -it -v $(pwd):/work --entrypoint "npx" ${IMAGE} textlint ${@}
'''
]