ARG VARIANT="24-bullseye@sha256:89cc6797542b34f5473e08302d8e117d2f5437a86c5efe6abc4b82f8812c19a0"
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:${VARIANT}

RUN apt update && apt install -y vim
RUN yarn global add zenn-cli@0.1.155
