---
name: renovate config validate

on:
  pull_request:
    paths:
      - default.json
      - renovate.json

jobs:
  validate:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: "renovate.json"
