---
name: renovate config validate

on:
  pull_request:
    paths:
      - default.json
      - renovate.json

jobs:
  validate:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: "renovate.json"
