---
name: renovate config validate

on:
  pull_request:
    paths:
      - default.json
      - renovate.json

jobs:
  validate:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: "renovate.json"
