name: textlint
on: [pull_request]
jobs:
  textlint:
    if: ${{ github.actor != 'renovate[bot]' }}
    name: runner / textlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '17'
      - run: yarn install
      - uses: reviewdog/action-setup@3f401fe1d58fe77e10d665ab713057375e39b887 # v1.3.0
        with:
          reviewdog_version: 'v0.14.2'
      - name: textlint | reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:  yarn run textlint -f checkstyle "articles/**" "books/**" | reviewdog -f=checkstyle -name="textlint" -reporter=github-pr-review
