name: textlint
on: [pull_request]
jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '17'
      - run: npm install
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: textlint | reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:  npx textlint -f checkstyle "articles/**" "books/**" | reviewdog -f=checkstyle -name="textlint" -reporter=github-pr-review
