---
name: Run typos

on: [pull_request]

jobs:
  typos:
    if: ${{ github.actor != 'renovate[bot]' }}
    name: Run typos
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: typos
        uses: crate-ci/typos@5edf45b39e546b1ff8af3ee205d68969434d8138 # v1.16.13
