---
name: Run typos

on: [pull_request]

jobs:
  typos:
    if: ${{ github.actor != 'renovate[bot]' }}
    name: Run typos
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: typos
        uses: crate-ci/typos@b86466d268920e98b8f1acc7fbb6f08ec871d136 # v1.24.1
