---
name: Run typos

on: [pull_request]

jobs:
  typos:
    if: ${{ github.actor != 'renovate[bot]' }}
    name: Run typos
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: typos
        uses: crate-ci/typos@v1.14.5
