---
name: Run typos

on: [pull_request]

jobs:
  typos:
    if: ${{ github.actor != 'renovate[bot]' }}
    name: Run typos
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: typos
        uses: crate-ci/typos@f12cee1d8f3c79282a98ecb41d235aef17dfa8fd # v1.25.0
