---
name: Run typos

on: [pull_request]

jobs:
  typos:
    if: ${{ github.actor != 'renovate[bot]' }}
    name: Run typos
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: typos
        uses: crate-ci/typos@bcafd462cb07ef7ba57e34abf458fe20767e808b # v1.19.0
