---
name: Run typos

on: [pull_request]

jobs:
  typos:
    name: Run typos
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: typos
        uses: crate-ci/typos@v1.5.0
